Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parcial.Data;

namespace Parcial.Controllers
{
    public class AlumnoController : Controller
    {

        private readonly IbookServices _bookServices;
        
        
        public AlumnoController(IbookServices bookServices)
        {
            _bookServices =bookServices;
        }

        // GET: Autor
        [Authorize(Roles="Administrador,Alumno")]
         public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrador,Alumno")]
        public ActionResult VerLibrosDisponibles(string searchTerm)
        {
            var librosDisponibles = _bookServices.GetBooksAvailable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                if (Enum.TryParse(searchTerm, true, out GeneroType generoType))
                {
                    librosDisponibles = librosDisponibles.Where(libro => libro.Genero == generoType).ToList();
                }
                else if (int.TryParse(searchTerm, out int year))
                {
                    librosDisponibles = librosDisponibles.Where(libro => libro.Año == year).ToList();
                }
                else
                {
                    string searchTermLower = searchTerm.ToLower();
                    librosDisponibles = librosDisponibles.Where(libro =>
                        libro.Nombre.ToLower().Contains(searchTermLower) ||
                        libro.Editorial.ToLower().Contains(searchTermLower)
                    ).ToList();
                }
            }

            var librosDisponiblesViewModel = librosDisponibles.Select(libro => new BookCreateViewModel
            {
                Id = libro.Id,
                AutorId = libro.AutorId,
                Nombre = libro.Nombre,
                Editorial = libro.Editorial,
                Año = libro.Año,
                Genero = libro.Genero,
                EstaReservado = libro.EstaReservado,
            }).ToList();

            return View(librosDisponiblesViewModel);
        }


        [Authorize(Roles="Administrador,Alumno")]
        public ActionResult VerCategorias(){
            var categorias = _bookServices.GetCategorias();
            var librosEnCategoriasViewModel = new List<LibrosEnCategoriaViewModel>();
            foreach(var categoria in categorias)
            {
                var librosEnCategorias = new LibrosEnCategoriaViewModel
                {
                    Categoria=categoria,
                    Libros= _bookServices.GetByCategoriaId(categoria.Id)
                };
                librosEnCategoriasViewModel.Add(librosEnCategorias);
            }

            return View(librosEnCategoriasViewModel);
        }

        [Authorize(Roles="Administrador,Alumno")]
        public ActionResult ReservarLibro()
        {
            var librosDisponibles = _bookServices.GetBooksAvailable();
            var bookViewModel = new BookViewModel
            {
                Books = librosDisponibles
            };
            return View(bookViewModel);
        }


        [HttpPost]
        [Authorize(Roles="Administrador,Alumno")]
        public ActionResult ConfirmarReserva(int[] libroIds)
        {
            foreach (int libroId in libroIds)
            {
            var libro = _bookServices.GetById(libroId);

             if (libro != null)
            {
            libro.EstaReservado = true;
            _bookServices.Reservar(libro);
            }
             }
    
            return RedirectToAction("Index");
        }
        
        [Authorize(Roles="Administrador,Alumno")]
        public ActionResult DevolverLibro()
        {
            var librosDisponibles = _bookServices.GetBooksUnAvailable();
            var bookViewModel = new BookViewModel
            {
                Books = librosDisponibles
            };
            return View(bookViewModel);
        }


        [HttpPost]
        [Authorize(Roles="Administrador,Alumno")]
        public ActionResult ConfirmarDevolucion(int[] libroIds)
        {
            foreach (int libroId in libroIds)
            {
                var libro = _bookServices.GetById(libroId);

                if (libro != null)
                {
                    libro.EstaReservado = false;
                    _bookServices.Devolver(libro);
                }
            }
        return RedirectToAction("Index");
        }

        public IActionResult DownloadTable()
        {
            List<LibrosEnCategoriaViewModel> model = GetYourTableData();

            StringBuilder sb = new StringBuilder();

            foreach (var categoria in model)
            {
                sb.AppendLine("Categoría: " + categoria.Categoria.Nombre);
                
                if (categoria.Libros.Count > 0)
                {
                    foreach (var libro in categoria.Libros)
                    {
                        sb.AppendLine("- " + libro.Nombre);
                    }
                }
                else
                {
                    sb.AppendLine("No hay libros en esta categoría.");
                }

                sb.AppendLine();
            }

            byte[] fileContents = Encoding.UTF8.GetBytes(sb.ToString());

            string fileName = "tabla.txt";
            string contentType = "text/plain";
            return File(fileContents, contentType, fileName);
        }

        private List<LibrosEnCategoriaViewModel> GetYourTableData()
        {
            var categorias = _bookServices.GetCategorias();
            var librosEnCategoriasViewModel = new List<LibrosEnCategoriaViewModel>();

            foreach (var categoria in categorias)
            {
                var librosEnCategorias = new LibrosEnCategoriaViewModel
                {
                    Categoria = categoria,
                    Libros = _bookServices.GetByCategoriaId(categoria.Id)
                };

                librosEnCategoriasViewModel.Add(librosEnCategorias);
            }

            return librosEnCategoriasViewModel;
        }





    }
}

Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parcial.Data;

namespace Parcial.Controllers
{
    public class ProfesorController : Controller
    {
      private readonly ILogger<HomeController> _logger;
      private readonly UserManager<IdentityUser> _userManager;
      private readonly RoleManager<IdentityRole> _roleManager;

    public ProfesorController (
        ILogger<HomeController> logger,
        UserManager<IdentityUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        _logger = logger;
        _userManager = userManager;
        _roleManager = roleManager;
    }

        // GET: Autor
        [Authorize(Roles="Administrador,Profesor")]
         public ActionResult Index()
        {
            return View();
        }

         [Authorize(Roles="Administrador,Profesor")]
        public async Task<ActionResult> UsuariosConRoles()
         {
            var usuarios = await _userManager.Users.ToListAsync();
            var roles = await _roleManager.Roles.ToListAsync();
            var usuariosConRoles = new List<UsuariosConRolesViewModel>();

               foreach (var usuario in usuarios)
               {
                  var usuarioRoles = await _userManager.GetRolesAsync(usuario);
                  var rolAsignado = roles.FirstOrDefault(r => usuarioRoles.Contains(r.Name));

                  usuariosConRoles.Add(new UsuariosConRolesViewModel
                  {
                        Usuario = usuario,
                        Rol = rolAsignado != null ? rolAsignado.Name : "Sin rol asignado"
                  });
               }

               return View(usuariosConRoles);

         }

       [Authorize(Roles="Administrador,Profesor")]
        public ActionResult AdministrarAutores(){
           
           return RedirectToAction("Index", "Autor");
        }

        [Authorize(Roles="Administrador,Profesor")]
        public ActionResult AdministrarCategorias(){
           
           return RedirectToAction("Index", "Categoria");
        }

        [Authorize(Roles="Administrador,Profesor")]
        public ActionResult AdministrarLibros(){
           
           return RedirectToAction("Index", "Book");
        }

        [Authorize(Roles="Administrador,Profesor")]
        public ActionResult AdministrarUsuarios(){
           
           return RedirectToAction("Index", "Users");
        }

        [Authorize(Roles="Administrador,Profesor")]
        public ActionResult AdministrarRoles(){
           
           return RedirectToAction("Index", "Roles");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head class="head">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parcial</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/alumno.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/config.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/all.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Parcial.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Views/Shared/_Layout.cshtml.css" asp-append-version="true"/>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/Images/home_app_logo_FILL0_wght200_GRAD0_opsz40.png"  alt="Index" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown ms-2">
                            <div class="btn-group dropdown">
                                <a class="btn btn-light" href="@Url.Action("Index", "Alumno")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">
                                    <img src="~/Images/student-with-graduation-cap.png" alt="Index" /> Alumno
                                </a>
                                <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="visually-hidden">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="alumnoDropdown">
                                    <li><a class="dropdown-item" href="@Url.Action("VerLibrosDisponibles", "Alumno")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Ver Libros Disponibles</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("ReservarLibro", "Alumno")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Reservar Libro</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("DevolverLibro", "Alumno")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Devolver Libro</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("VerCategorias", "Alumno")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Ver Categorias</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <div class="btn-group dropdown ms-2">
                                <a class="btn btn-light" href="@Url.Action("Index", "Profesor")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">
                                    <img src="~/Images/teach.png" alt="Index" /> Profesor
                                </a>
                                <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="visually-hidden">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="alumnoDropdown">
                                    <li><a class="dropdown-item" href="@Url.Action("AdministrarAutores", "Profesor")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Administrar Autores</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("AdministrarCategorias", "Profesor")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Administrar Categorias</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("AdministrarLibros", "Profesor")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Administrar Libros</a></li>
                                    @if (User.IsInRole("Administrador")){
                                    <li><a class="dropdown-item" href="@Url.Action("AdministrarUsuarios", "Profesor")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Administrar Usuarios</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("AdministrarRoles", "Profesor")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Administrar Roles</a></li>
                                    }
                                    <li><a class="dropdown-item" href="@Url.Action("UsuariosConRoles", "Profesor")" style="color: rgb(0, 0, 0); text-align: center font-weight: bold;">Ver roles de Usuarios</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 ">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>